version: '2'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ${LOCAL_VOLUME}:/var/lib/postgresql/data

  fastapi:
    build:
      dockerfile: Dockerfile
      context: .
    image: "${IMAGE_NAME}"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
    ports:
      - ${CONTAINER_PORT}:8000
